#ifndef __FINGERPRINT_H__
#define __FINGERPRINT_H__

struct  fingerprint_driver{

int (*compare_id)(void) ;
int (*probe)(struct spi_device *spi) ;
int (*remove)(struct spi_device *spi) ;
struct mt_chip_conf * fp_spi_conf;

};

enum fingerprint_cs{
	MTK_SPI_TEST_CS=0, // It's 0,because mtk_spi_test is used.

#if defined(CONFIG_FINGERPRINT_SUNWAVECORP_NEW_REE) || defined(CONFIG_FINGERPRINT_SUNWAVECORP_REE) || defined(CONFIG_FINGERPRINT_SUNWAVECORP_NEW_TEE)
	FINGERPRINT_SUNWAVECORP_CS,
#endif
#if defined(CONFIG_FINGERPRINT_CHIPSAILING) || defined(CONFIG_FINGERPRINT_CHIPSAILING_TEE) || defined(CONFIG_FINGERPRINT_CHIPSAILING_REE)
	FINGERPRINT_CHIPSAILING_CS,
#endif

#if defined(CONFIG_FINGERPRINT_GOODIX_GF3258_REE_TEE)
	FINGERPRINT_GOODIX_GF3258_REE_TEE_CS,
#endif
#if defined(CONFIG_FINGERPRINT_GOODIX) || defined(CONFIG_FINGERPRINT_GOODIX_TEE)
	FINGERPRINT_GOODIX_CS,
#endif

#if defined(CONFIG_FINGERPRINT_MICROARRAY) || defined(CONFIG_FINGERPRINT_MICROARRAY_TEE) || defined(CONFIG_FINGERPRINT_AFS120N) || defined(CONFIG_FINGERPRINT_MICROARRAY_A80T) || defined(CONFIG_FINGERPRINT_MICROARRAY_A80T_TEE)
	FINGERPRINT_MICROARRAY_CS,
#endif

#if defined(CONFIG_FINGERPRINT_BETTERLIFE)
	FINGERPRINT_BETTERLIFE_TEE_CS,
#endif
#if defined(CONFIG_FINGERPRINT_ICN7152_TEE)
	FINGERPRINT_FPSENSOR_ICN7152_CS,
#endif
#if defined(CONFIG_FINGERPRINT_CDFINGER_FPS988E) || defined(CONFIG_FINGERPRINT_CDFINGER_TEE)
	FINGERPRINT_CDFINGER_CS,
#endif

#if defined(CONFIG_FINGERPRINT_CHIPONE_TEE) || defined(CONFIG_FINGERPRINT_CHIPONE_REE)
	FINGERPRINT_FPFINGER_CS,
#endif

      MAX_FINGER_CHIP_CS_NUMBER
};

#endif
