
#include "hct_common_config.h"
#include "mt6853-pinfunc.h"

/********************typec accdet***************/
//#define __HCT_TYPEC_ACCDET_MIC_SWITCH_GPIO_NUM__     108
/**************************Lcm Related*********/

#define __HCT_GPIO_LCD_BIAS_ENP_PINMUX__ PINMUX_GPIO137__FUNC_GPIO137//+5v
#define __HCT_GPIO_LCD_BIAS_ENP_PIN_NUM__  137

#define __HCT_GPIO_LCD_BIAS_ENN_PINMUX__ PINMUX_GPIO138__FUNC_GPIO138//-5V
#define __HCT_GPIO_LCD_BIAS_ENN_PIN_NUM__  138

#define __HCT_GPIO_LCM_POWER_DM_PINMUX__   	PINMUX_GPIO46__FUNC_GPIO46//1.8v
#define __HCT_GPIO_LCD_POWER_DM_PIN_NUM__	46

#define __HCT_GPIO_LCM_POWER_DP_PINMUX__   PINMUX_GPIO45__FUNC_GPIO45//2.8
#define __HCT_GPIO_LCD_POWER_DP_PIN_NUM__  45

#define __HCT_GPIO_LCD_RST_OUT_PINMUX__ PINMUX_GPIO86__FUNC_GPIO86
#define __HCT_GPIO_LCD_RST_OUT_PIN_NUM__    86

//led mode  4 -> cmd mode   5 -> vdo mode
#define __HCT_LED_MODE__ 4

/**************************Camera Related*********/

//-----------main camera
#define __HCT_GPIO_CAMERA_CMRST_PINMUX__ PINMUX_GPIO54__FUNC_GPIO54
#define __HCT_GPIO_CAMERA_CMPDN_PINMUX__ PINMUX_GPIO53__FUNC_GPIO53
#define __HCT_GPIO_CAMERA_VCAMD_PINMUX__ PINMUX_GPIO93__FUNC_GPIO93
#define __HCT_GPIO_CAMERA_VCAMA_PINMUX__ PINMUX_GPIO94__FUNC_GPIO94
#define __HCT_GPIO_CAMERA_VCAMAF_PINMUX__ PINMUX_GPIO132__FUNC_GPIO132
//#define __HCT_GPIO_CAMERA_VCAMD2_PINMUX__ PINMUX_GPIO17__FUNC_GPIO17
//#define __HCT_GPIO_CAMERA_VCAMA2_PINMUX__ PINMUX_GPIO31__FUNC_GPIO31
#define __HCT_GPIO_CAMERA_MCLKON_PINMUX__ PINMUX_GPIO49__FUNC_CMMCLK0
#define __HCT_GPIO_CAMERA_MCLKOFF_PINMUX__ PINMUX_GPIO49__FUNC_GPIO49

//-----------sub camera
#define __HCT_GPIO_CAMERA_SUB_CMRST_PINMUX__ PINMUX_GPIO60__FUNC_GPIO60
#define __HCT_GPIO_CAMERA_SUB_CMPDN_PINMUX__ PINMUX_GPIO59__FUNC_GPIO59
#define __HCT_GPIO_CAMERA_SUB_VCAMD_PINMUX__ PINMUX_GPIO140__FUNC_GPIO140
#define __HCT_GPIO_CAMERA_SUB_VCAMA_PINMUX__ PINMUX_GPIO131__FUNC_GPIO131
#define __HCT_GPIO_CAMERA_SUB_MCLKON_PINMUX__ PINMUX_GPIO52__FUNC_CMMCLK3
#define __HCT_GPIO_CAMERA_SUB_MCLKOFF_PINMUX__ PINMUX_GPIO52__FUNC_GPIO52

//-----------main2 camera
#define __HCT_GPIO_CAMERA_MAIN2_CMRST_PINMUX__ PINMUX_GPIO56__FUNC_GPIO56
#define __HCT_GPIO_CAMERA_MAIN2_CMPDN_PINMUX__ PINMUX_GPIO55__FUNC_GPIO55
#define __HCT_GPIO_CAMERA_MAIN2_VCAMD_PINMUX__ PINMUX_GPIO36__FUNC_GPIO36
#define __HCT_GPIO_CAMERA_MAIN2_VCAMA_PINMUX__ PINMUX_GPIO167__FUNC_GPIO167
#define __HCT_GPIO_CAMERA_MAIN2_MCLKON_PINMUX__ PINMUX_GPIO50__FUNC_CMMCLK1
#define __HCT_GPIO_CAMERA_MAIN2_MCLKOFF_PINMUX__ PINMUX_GPIO50__FUNC_GPIO50


//-----------main3 camera
#define __HCT_GPIO_CAMERA_MAIN3_CMRST_PINMUX__ PINMUX_GPIO58__FUNC_GPIO58
#define __HCT_GPIO_CAMERA_MAIN3_CMPDN_PINMUX__ PINMUX_GPIO57__FUNC_GPIO57
#define __HCT_GPIO_CAMERA_MAIN3_VCAMD_PINMUX__ PUNMUX_GPIO_NONE_FUNC_NONE	//PINMUX_GPIO110__FUNC_GPIO110
#define __HCT_GPIO_CAMERA_MAIN3_VCAMA_PINMUX__ PUNMUX_GPIO_NONE_FUNC_NONE	//PINMUX_GPIO112__FUNC_GPIO112
#define __HCT_GPIO_CAMERA_MAIN3_MCLKON_PINMUX__ PINMUX_GPIO51__FUNC_CMMCLK2
#define __HCT_GPIO_CAMERA_MAIN3_MCLKOFF_PINMUX__ PINMUX_GPIO51__FUNC_GPIO51


//-----------fake camera
//#define __HCT_GPIO_CAMERA_MAIN_FAKE_CMRST_PINMUX__ PINMUX_GPIO87__FUNC_GPIO87
//#define __HCT_GPIO_CAMERA_MAIN_FAKE_CMPDN_PINMUX__ PINMUX_GPIO160__FUNC_GPIO160

//-----------mipi switch
#define __HCT_GPIO_CAMERA_MIPI_SWITCH_EN_PINMUX__ PUNMUX_GPIO_NONE_FUNC_NONE	//PINMUX_GPIO170__FUNC_GPIO170
#define __HCT_GPIO_CAMERA_MIPI_SWITCH_SEL_PINMUX__ PUNMUX_GPIO_NONE_FUNC_NONE	//PINMUX_GPIO171__FUNC_GPIO171

/**************************USB Related****************/
#define __HCT_MT6360_USB_EINT_PIN_NUM__			10
#define __HCT_MT6360_TYPEC_PD_PIN_NUM__			9

/************************** RT9750 ****************/
#ifdef CONFIG_LOAD_SWITCH_RT9750
#define __HCT_RT9750_CHARGE_EN_PIN_NUM__		187
#define __HCT_RT9750_CHARGE_EINT_PIN_NUM__		1
#endif

/**************************FINGERPRINT SUPPORT****************/
#ifdef CONFIG_HCT_FINGERPRINT_SUPPORT
#define __HCT_FINGERPRINT_EINT_EN_PIN_NUM__	48
#define __HCT_FINGERPRINT_EINT_PIN__	PINMUX_GPIO48__FUNC_GPIO48

#define __HCT_FINGERPRINT_RESET_PIN_NUM__ 47
#define __HCT_FINGERPRINT_RESET_PIN__	PINMUX_GPIO47__FUNC_GPIO47
#endif

/**************************Custom Key****************/

#define __HCT_INTERCOMKEY_EINT_EN_PIN_NUM__    81
#define __HCT_INTERCOMKEY_EINT_PIN__           PINMUX_GPIO81__FUNC_GPIO81
#define __HCT_INTERCOMKEY_EINT_GPIO_NUM__      81

#define __HCT_INTERCOMKEY2_EINT_EN_PIN_NUM__    82
#define __HCT_INTERCOMKEY2_EINT_PIN__           PINMUX_GPIO82__FUNC_GPIO82
#define __HCT_INTERCOMKEY2_EINT_GPIO_NUM__      82

#include "hct_custom_config.h"

